services:
  mongo:
    image: mongodb/mongodb-community-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P4ss
      MONGO_INITDB_DATABASE: todosdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - compose-network

  app:
    build: .
    environment:
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - "8081:8081"
    networks:
      - compose-network
    depends_on:
      - mongo

networks: 
    compose-network:
      driver: bridge
volumes:
  mongodb_data: 
