on: [push]

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        acrName: todoregister
        containerAppName: rennanprysthon/todoapp
        resourceGroup: todo-app-poc
        imageToDeploy: myregistry.azurecr.io/app:${{ github.sha }}


